# Generated by Django 5.0.3 on 2024-04-02 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.message'),
            preserve_default=False,
        ),
    ]
