# Generated by Django 5.0.3 on 2024-04-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_message_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='forum',
            name='tags',
            field=models.ManyToManyField(to='forum.forumtag'),
        ),
    ]
