# Generated by Django 5.0.3 on 2024-04-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forumtag_forum_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='nama',
            new_name='judul',
        ),
        migrations.AddField(
            model_name='forum',
            name='deskripsi',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
