# Generated by Django 5.0.3 on 2024-04-11 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_nama_forum_judul_forum_deskripsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='forum',
            name='tags',
        ),
        migrations.AddField(
            model_name='forum',
            name='categories',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='forum.category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ForumTag',
        ),
    ]
