# Generated by Django 5.0.3 on 2024-04-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_category_remove_forum_tags_forum_categories_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Kategori',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='categories',
            new_name='kategori',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='creator',
            new_name='kreator',
        ),
        migrations.RenameField(
            model_name='kategori',
            old_name='name',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='reply_to',
            new_name='membalas_ke',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='pengirim',
        ),
    ]
