# Generated by Django 5.0.3 on 2024-04-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_forum_kategori_forum_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='jumlah_pesan',
            field=models.IntegerField(default=0),
        ),
    ]
