# Generated by Django 5.0.4 on 2024-04-29 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_forum_created_at_message_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='membalas_ke',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.message'),
        ),
    ]
