# Generated by Django 5.0.4 on 2024-06-02 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_message_membalas_ke'),
        ('user_profile', '0006_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='kreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='pengirim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
    ]
