# Generated by Django 5.0.6 on 2024-06-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_forum_kreator_alter_message_pengirim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='kategori',
        ),
        migrations.AddField(
            model_name='forum',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.kategori'),
        ),
    ]
