# Generated by Django 5.0.3 on 2024-04-01 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keranjang', '0001_initial'),
        ('makanan', '0002_kategori_makanan_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemKeranjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(default=0)),
                ('keranjang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keranjang.keranjang')),
                ('makanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makanan.makanan')),
            ],
        ),
    ]
