# Generated by Django 5.0.3 on 2024-04-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keranjang', '0003_remove_itemkeranjang_keranjang_itemkeranjang_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemkeranjang',
            name='jumlah',
            field=models.IntegerField(default=1),
        ),
    ]
