# Generated by Django 5.0.4 on 2024-06-02 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keranjang', '0004_alter_itemkeranjang_jumlah'),
        ('user_profile', '0006_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemkeranjang',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
    ]
