# Generated by Django 5.0.3 on 2024-04-08 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_order_makanan_order_orderid_and_more'),
        ('review', '0004_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
