# Generated by Django 5.0.3 on 2024-04-08 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_review_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='nilai',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='reply',
            field=models.TextField(null=True),
        ),
    ]
