# Generated by Django 5.0.3 on 2024-04-23 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0003_alter_kategori_nama'),
        ('review', '0008_review_toko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='toko',
        ),
        migrations.AddField(
            model_name='review',
            name='makanan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='makanan.makanan'),
        ),
    ]
