# Generated by Django 5.0.3 on 2024-04-23 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_remove_review_toko_review_makanan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reply',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='review.review')),
            ],
        ),
    ]
