# Generated by Django 5.0.3 on 2024-04-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_remove_review_reply_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
