# Generated by Django 5.0.3 on 2024-04-23 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_review_reply_delete_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='nilai',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
