# Generated by Django 5.0.3 on 2024-06-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='komentar',
            field=models.TextField(default='-', null=True),
        ),
    ]
