# Generated by Django 5.0.3 on 2024-03-29 16:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('harga', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('deskripsi', models.TextField()),
                ('stok', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko.toko')),
            ],
        ),
    ]
