# Generated by Django 5.0.3 on 2024-04-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0003_alter_kategori_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='makanan',
            name='img_url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
