# Generated by Django 5.0.4 on 2024-04-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0004_makanan_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makanan',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='makanan',
            name='deskripsi',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
