# Generated by Django 5.0.3 on 2024-03-23 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nama', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('saldo', models.FloatField(default=0)),
                ('role', models.CharField(choices=[('penjual', 'Penjual'), ('pembeli', 'Pembeli')], max_length=7)),
            ],
        ),
    ]
