# Generated by Django 5.0.3 on 2024-03-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pfp_url',
            field=models.TextField(default='https://i.quotev.com/hiaa3fa55smq.jpg'),
        ),
    ]
