# Generated by Django 5.0.4 on 2024-04-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_rename_nama_profile_nama_lengkap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('PENJUAL', 'Penjual'), ('PEMBELI', 'Pembeli')], max_length=7),
        ),
    ]
