# Generated by Django 5.0.4 on 2024-04-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('penjual', 'Penjual'), ('pembeli', 'Pembeli')], max_length=7),
        ),
    ]
