# Generated by Django 5.0.4 on 2024-06-02 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_profile', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
