# Generated by Django 5.0.3 on 2024-04-20 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_date_added'),
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='toko',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='toko.toko'),
            preserve_default=False,
        ),
    ]
