# Generated by Django 5.0.3 on 2024-04-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ordergroup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='total_harga',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
