# Generated by Django 5.0.3 on 2024-04-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_ordergroup_total_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DIPESAN', 'Dipesan'), ('DIPROSES', 'Diproses'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], default='DIPESAN', max_length=10),
        ),
    ]
